Repository select2/select2, pull requests merged in 2019-07, with the labels that each got.

#5564 remove deprecated jQuery shorthand
  src/js/select2/data/tokenizer.js
  src/js/select2/dropdown/search.js
  src/js/select2/selection/base.js
  src/js/select2/selection/search.js
  src/js/select2/selection/single.js
Labels: 4.x, compatibility

#5575 Fix infinite scroll when the scrollbar is not visible
  src/js/select2/dropdown/infiniteScroll.js
  tests/results/infiniteScroll-tests.js
  tests/unit-jq1.html
  tests/unit-jq2.html
  tests/unit-jq3.html
Labels: 4.x

#5576 Revert change to focusing behaviour in 4.0.6
  src/js/select2/selection/base.js
  tests/selection/focusing-tests.js
  tests/unit-jq1.html
  tests/unit-jq2.html
  tests/unit-jq3.html
Labels: 4.x

#5579 Mirror disabled state through aria-disabled on selection
  src/js/select2/selection/base.js
  tests/a11y/selection-tests.js
Labels: 4.x

#5580 Do not propagate click when search box is not empty
  src/js/select2/selection/search.js
  tests/selection/search-tests.js
Labels: 4.x

#5581 Fix `maximumSelectionLength` being ignored by `closeOnSelect`
  src/js/select2/data/maximumSelectionLength.js
  tests/data/maximumSelectionLength-tests.js
Labels: 4.x

#5586 Fix generated options not receiving result IDs
  src/js/select2/data/array.js
  tests/data/array-tests.js
  tests/data/inputData-tests.js
Labels: 4.x

#5587 Select2 now clears the internal ID when it is destroyed
  src/js/select2/utils.js
  tests/unit-jq1.html
  tests/unit-jq2.html
  tests/unit-jq3.html
  tests/utils/data-tests.js
Labels: 4.x

#5589 Remove selection title attribute if text is empty
  src/js/select2/selection/multiple.js
  src/js/select2/selection/single.js
  tests/selection/multiple-tests.js
  tests/selection/single-tests.js
Labels: 4.x

#5590 Reposition dropdown whenever items are selected
  src/js/select2/dropdown/attachBody.js
Labels: 4.x

#5592 Fix dropdown positioning when displayed above with messages
  src/js/select2/dropdown/attachBody.js
Labels: 4.x

#5595 Fix search box expanding width of container
  src/js/select2/selection/search.js
  tests/selection/search-placeholder-tests.js
  tests/selection/search-tests.js
  tests/unit-jq1.html
  tests/unit-jq2.html
  tests/unit-jq3.html
Labels: 4.x

#5582 Set the main ARIA 1.1 roles and properties for comboboxes
  src/js/select2/dropdown/infiniteScroll.js
  src/js/select2/dropdown/search.js
  src/js/select2/results.js
  src/js/select2/selection/search.js
  tests/a11y/search-tests.js
  tests/dropdown/search-a11y-tests.js
  tests/results/a11y-tests.js
  tests/results/option-tests.js
  tests/selection/search-a11y-tests.js
  tests/unit-jq1.html
  tests/unit-jq2.html
  tests/unit-jq3.html
Labels: 4.x, accessibility, status: pending PR merge
