Repository select2/select2, pull requests merged in 2019-06, with the labels that each got.

#5527 Automatically deploy to NPM
  .travis.yml
  Gruntfile.js
Labels: 4.x, meta

#5528 Clean up docs
  .travis.yml
  README.md
Labels: documentation

#5521 Improve French Translation
  src/js/select2/i18n/fr.js
Labels: 4.x, feature: translation/i18n, status: pending PR merge

#5508 removed select2-selection__placeholder from _multiple.scss
  src/scss/theme/default/_multiple.scss
Labels: 4.x, enhancement, feature: selections

#5531 Test against jQuery 3.4.1
  tests/data/array-tests.js
  tests/data/select-tests.js
  tests/dropdown/positioning-tests.js
  tests/integration-jq3.html
  tests/unit-jq3.html
  tests/vendor/jquery-3.4.1.js
Labels: 4.x, compatibility
