Repository select2/select2, pull requests merged in 2020-01, with the labels that each got.

#5741 Fix Contribute link
  README.md
Labels: 4.x, status: pending PR merge

#4649 Trigger 'input' event before 'change' events
  src/js/select2/compat/inputData.js
  src/js/select2/core.js
  src/js/select2/data/select.js
  src/js/select2/selection/allowClear.js
  tests/data/select-tests.js
Labels: 4.x, compatibility, status: pending PR merge

#5513 Feed back the keypress code that was responsible for the 'close' even…
  src/js/select2/core.js
Labels: 4.x

#5734 Only trigger 'selection:update' once on DOM change events
  src/js/select2/core.js
  tests/integration/dom-changes.js
Labels: 4.x, enhancement, feature: selections

#5751 Prevent opening of disabled elements
  src/js/select2/core.js
  src/js/select2/selection/allowClear.js
  src/js/select2/selection/base.js
  src/js/select2/selection/multiple.js
  tests/selection/openOnKeyDown-tests.js
  tests/unit-jq1.html
  tests/unit-jq2.html
  tests/unit-jq3.html
Labels: 4.x, status: pending PR merge
