Repository select2/select2, pull requests merged in 2021-01, with the labels that each got.

#5957 Update fr.js
  src/js/select2/i18n/fr.js
Labels: 4.x, feature: translation/i18n, status: pending PR merge

#5942 Add aria-controls attribute for combobox to fix accesibility issue
  src/js/select2/selection/single.js
Labels: 4.x, accessibility

#5824 Add aria-label 'Search' to search input when dropdown opens.
  src/js/select2/dropdown/search.js
  src/js/select2/i18n/en.js
  src/js/select2/selection/search.js
  tests/dropdown/search-a11y-tests.js
  tests/options/translation-tests.js
  tests/selection/search-a11y-tests.js
Labels: 4.x, accessibility, feature: search, feature: translation/i18n, status: pending PR merge

#5965 Fix slow memory leak caused by not clearing cache
  src/js/select2/core.js
Labels: 4.x

#5806 Allow pasting multiple lines into the search field for tokenization
  src/js/select2/selection/allowClear.js
  src/js/select2/selection/search.js
  src/scss/_multiple.scss
  src/scss/theme/default/_multiple.scss
  tests/selection/search-a11y-tests.js
  tests/selection/search-placeholder-tests.js
  tests/selection/search-tests.js
Labels: 4.x, enhancement, feature: multi-select, feature: search, feature: tagging, status: pending PR merge

#5759 Changed tab key press to behave the same as enter key and select the highlighted option
  src/js/select2/core.js
Labels: 4.x, enhancement, feature: selections

#5812 Update highlightFirstItem to take tags in to consideration
  src/js/select2/data/tags.js
  src/js/select2/defaults.js
  src/js/select2/dropdown/tagsSearchHighlight.js
  tests/results/focusing-tests.js
Labels: 4.x, enhancement, feature: tagging

#5973 Set title for single select placeholder
  src/js/select2/selection/placeholder.js
  tests/selection/placeholder-tests.js
Labels: 4.x, accessibility, enhancement, feature: placeholders
